### ISSUE TITLE
Limit the values of the origin 

### ISSUE THREAD

**Issue by statasaurus** [atorus-research/metacore#27]
https://github.com/atorus-research/metacore/blob/c583332b81f2473bb3562b847a9a2803130c60e7/R/validators.R#L226

@mstackhouse is it possible to limit the origin options to eCRF, Derived, Predecessor, and Assigned? Are those all the options?

**Comment by mstackhouse** [comment]
@statasaurus Here are the snippets from the latest Define standard. This has changed quite a bit from last time I looked. This is for the Define standard 2.1.3

SDTM
===
![image](https://user-images.githubusercontent.com/31387567/149783218-6f24afb5-2805-49ab-9413-f366ab1c03e4.png)

ADaM
===
![image](https://user-images.githubusercontent.com/31387567/149783291-26d49e19-87c9-4770-8089-b03a784ce3c0.png)

The collected ones from the eCRF are the most complicated, because you have associated page numbers:
![image](https://user-images.githubusercontent.com/31387567/149784386-b84da849-d6d4-497b-97a3-333bc465c5f1.png)

**Comment by mstackhouse** [comment]
@statasaurus The link to the guide is right here but you need a CDISC account to get the file. 
https://www.cdisc.org/standards/foundational/define-xml/define-xml-v2-1
